spring.application.name=blog-backend

# ????????? H2
spring.datasource.url=jdbc:h2:mem:blogdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

logging.level.org.springframework.jdbc.core=DEBUG

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB