DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS post_tags;
DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id BIGINT AUTO_INCREMENT  PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    text TEXT NOT NULL,
    likes_count INT DEFAULT 0,
    image_data BLOB
);

CREATE TABLE post_tags (
    post_id BIGINT NOT NULL,
    tag VARCHAR(100) NOT NULL,
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);

CREATE TABLE comments (
    id BIGINT AUTO_INCREMENT  PRIMARY KEY,
    post_id BIGINT NOT NULL,
    text VARCHAR(1000) NOT NULL,
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);